name: Data Management Zone Destroy
permissions:
  id-token: write
  contents: read
  pull-requests: write
on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    uses: ./.github/workflows/_terraformDestroyTemplate.yml
    name: "Terraform Destroy"

    with:
      environment: "dev"
      terraform_version: "1.10.2"
      node_version: 20
      working_directory: "./tests/e2e"
      tenant_id: "95878d2e-5f12-487f-b454-aa5fe0db12a2"
      subscription_id: "64d97042-a8b5-4033-b2d1-4bbda40c8a91"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
