name: Data Management Zone Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"

  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"

jobs:
  terraform_deploy:
    uses: ./.github/workflows/_terraformEnvironmentTemplate.yml
    name: "Terraform Deploy"
    with:
      environment: "dev"
      terraform_version: "1.10.2"
      node_version: 20
      working_directory: "./tests/e2e"
      tenant_id: "95878d2e-5f12-487f-b454-aa5fe0db12a2"
      subscription_id: "64d97042-a8b5-4033-b2d1-4bbda40c8a91"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

#  terraform_destroy:
#    uses: ./.github/workflows/_terraformDestroyTemplate.yml
#    name: "Terraform Destroy"
#    needs: [terraform_deploy]
#    if: github.event_name == 'push' || github.event_name == 'release'
#    with:
#      environment: "dev"
#      terraform_version: "1.10.2"
#      node_version: 20
#      working_directory: "./tests/e2e"
#      tenant_id: "395878d2e-5f12-487f-b454-aa5fe0db12a2"
#      subscription_id: "64d97042-a8b5-4033-b2d1-4bbda40c8a91"
#    secrets:
#      CLIENT_ID: ${{ secrets.CLIENT_ID }}
